site_name: ECE搭车客指南

theme:
  name: mkdocs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - content.code.annotate

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - attr_list

nav:
  - 首页: 'index.md'
  - 初心与使命: '初心和使命.md'
  - ECE120: 
      - 序: 'ECE120/序.md'
      - 第一章: 'ECE120/Chapter1.md'
      - 第二章: 'ECE120/Chapter2.md'
      - 第三章: 'ECE120/Chapter3.md'
      - 第四章: 'ECE120/Chapter4.md'
  - ECE220:
      - 序: 'ECE220/序.md'



